### ISSUE TITLE
Line 30 mocha test impossible to pass -- chg calledOnce to called

### ISSUE THREAD

**Issue by jeremygottfried** [learn-co-curriculum/js-basics-arithmetic-lab#1]
`  it("invokes 'Math.random()'", function () {
      expect(spyOnMathRandom.calledOnce).to.be.true;
    });
  });`

CHANGE TO : 

  ` it("invokes 'Math.random()'", function () {
      expect(spyOnMathRandom.**called**).to.be.true;
    });
  }); `

**Comment by maxwellbenton** [comment]
Hi @jeremygottfried,

I'm was not able to reproduce this issue, but tested both `calledOnce` and `called` and confirmed that both will work, so I've updated the test in this lesson.

If you don't believe this has resolve the issue, I'd be happy to take a second look!

As always, thanks for contributing! 💙
