### ISSUE TITLE
My code is correct, but I can't pass the test.

### ISSUE THREAD

**Issue by tech-chieftain** [learn-co-curriculum/js-basics-arithmetic-lab#2]
I wrote the code for this lab as intended but for some reason the test can't identify that I have invoked Math.random(), although I did. I tried different codes and methods but they don't seem to work.

**Comment by drakeltheryuujin** [comment]
Hi @tech-chieftain,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by tech-chieftain** [comment]
HI @drakeltheryuujin,

I understand what you're saying, but as I stated above I'm 100% sure that my code is correct.
Anyways, I checked and found that another student had the same issue (Check issue #1 ) and found that the way he suggested correctly made me pass the test. 
Thank you.
