### ISSUE TITLE
The instructions in this lab don't match

### ISSUE THREAD

**Issue by sammy-brake** [learn-co-curriculum/js-basics-arithmetic-lab#6]
In the [lab page](https://learn.co/tracks/full-stack-web-development-v6/javascript/basics/arithmetic-lab?batch_id=306&track_id=43149), the assignment directions are: 

Assignment
There are four challenges we need you to solve. Code your solution in index.js. We'll provide some brief instructions here, but you should really rely on the test failure messages to guide your code.

Instructions
Create a variable called multiply that will multiply var1 and var2 whose results will equal "62".
Create a variable called random that will generate a random integer greater than 0.
Create a variable called mod set to an equation whose remainder is equal to "4".
Create a variable called max that will return "20" as the highest number in the set.

However, those directions don't at all match the tests.

**Comment by sgharms** [comment]
Hi @sammy-brake. We appear to have had a deployment error to the v-000 version of this curriculum. Is the problem solved now?

**Comment by jaredkgrove** [comment]
I just completed this lesson and the README differs between the learn website and github. The tests still correspond to the instructions on github.

**Comment by sgharms** [comment]
Wow, OK. There appears to be a deployment bug going on here that your input has allowed me to verify and reproduce. I've opened a support ticket on Learn to get this force updated. Sorry for the confusion during your educational journey.

**Comment by sgharms** [comment]
I think it's fixed. I just ran this based on pulling from the v-000 (online self paced v7 track):

```text
➜  /tmp git clone git@github.com:learn-co-students/js-basics-arithmetic-lab-v-000 helloAmanda > /dev/null
Cloning into 'helloAmanda'...
remote: Enumerating objects: 95, done.
remote: Total 95 (delta 0), reused 0 (delta 0), pack-reused 95
Receiving objects: 100% (95/95), 70.09 KiB | 5.39 MiB/s, done.
Resolving deltas: 100% (42/42), done.
➜  /tmp cd helloAmanda
➜  helloAmanda git:(master) head -20 test/indexTest.js
const chai = require('chai')
const expect = chai.expect;

describe('index.js', function() {
  describe('multiply', function() {
    it("is an equation whose multiplied results will equal 62", function() {
      expect(var1).to.be.a('number')
      expect(var2).to.be.a('number')
      expect(multiply).to.eq(62)
    });
  });
  describe('random', function() {
    it("is generates a random integer greater than 0", function() {
      expect(random).to.be.a('number')
      expect(random).to.not.eq(0)
    });
  });
  describe('mod', function() {
    it("is generates a remainder that is equal to 4", function() {
      expect(mod).to.eq(4)
➜  helloAmanda git:(master) grep -A5 Instructions README.md
## Instructions

1. Create a variable called `multiply` that will multiply `var1` and `var2`
   whose results will equal "62".
2. Create a variable called `random` that will generate a random integer greater
   than 0.
```

Can you confirm?

**Comment by jaredkgrove** [comment]
I think it looks good now. Thanks
